- name: Main
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    data_file: config/default.yml
    vault_file: data/vault.yml
    intersight_review: {}
    api_info: &api_info
      api_private_key: data/secret.txt
      api_key_id: "{{ vault_api_key }}"
      api_uri: "{{ intersight_url | default(omit) }}"

  pre_tasks:
    - name: Include vault data
      ansible.builtin.include_vars: "{{ vault_file }}"
      tags: always
    - name: Load data
      ansible.builtin.include_vars: "{{ data_file }}"
      tags: always
    - name: Set API info
      ansible.builtin.set_fact:
        api_info: "{{ api_info }}"
      tags: always
    - name: Set Configuration data
      ansible.builtin.set_fact:
        data: "{{ Intersight }}"
      tags: always
    - name: Set Config data
      ansible.builtin.set_fact:
        config: "{{ config }}"
      tags: always

  tasks:
    - name: Get info for servers by name
      cisco.intersight.intersight_info:
        <<: *api_info
        server_names: []
      register: server_names

    - name: Build Server Output
      ansible.builtin.set_fact:
        server_output: "{{ server_output | default([]) + [{'Name': item.Name, 'Data': {'Moid': item.Moid}}] }}"
      loop: "{{ server_names.intersight_servers }}"
      loop_control:
        label: All data gathered from Intersight for server {{ item.Name }}

    - name: Update intersight_review server details
      ansible.builtin.set_fact:
        intersight_review: "{{ intersight_review | combine({'intersight': {'server': {'servers': server_output}}}, recursive=True) }}"

    - name: Get first record
      ansible.builtin.debug:
        msg: "{{ intersight_review | get_value('intersight.server.servers[1]') }}"

    - name: Get one specifically named record
      ansible.builtin.debug:
        msg: "{{ intersight_review | get_value('intersight.server.servers[Name==`B03-IMM-FI-1-3`]') }}"

    - name: Server Count
      ansible.builtin.debug:
        msg: "{{ intersight_review | get_value('intersight.server.servers') | length }}"

    - name: Display all servers names
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ intersight_review | get_value('intersight.server.servers[*].Name') }}"


    - name: Display all servers MOIDS
      ansible.builtin.debug:
        var: item
      loop: "{{ intersight_review | get_value('intersight.server.servers[*].Data.Moid') }}"

    - name: Extend a server record
      ansible.builtin.set_fact:
        intersight_review: "{{ intersight_review | add_key_value('intersight.server.servers[Name==`Dell-PowerEdge R650-J4OVC3INDUM1V1`].Type', 'Dell') }}"

    - name: Get one specifically named record
      ansible.builtin.debug:
        msg: "{{ intersight_review | get_value('intersight.server.servers[Name==`Dell-PowerEdge R650-J4OVC3INDUM1V1`]') }}"

    - name: Extend all records - outside Data
      ansible.builtin.set_fact:
        intersight_review: "{{ intersight_review | add_key_value('intersight.server.servers[*].Data.added', 'now') }}"

    - name: Display record 1
      ansible.builtin.debug:
        msg: "{{ intersight_review | get_value('intersight.server.servers[1]') }}"
