- name: Main
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    data_file: config/default.yml
    vault_file: data/vault.yml
    intersight_review: {}
    api_info: &api_info
      api_private_key: data/secret.txt
      api_key_id: "{{ vault_api_key }}"
      api_uri: "{{ intersight_url | default(omit) }}"

  pre_tasks:
    - name: Include vault data
      ansible.builtin.include_vars: "{{ vault_file }}"
      tags: always
    - name: Load data
      ansible.builtin.include_vars: "{{ data_file }}"
      tags: always
    - name: Set API info
      ansible.builtin.set_fact:
        api_info: "{{ api_info }}"
      tags: always
    - name: Set Configuration data
      ansible.builtin.set_fact:
        data: "{{ Intersight }}"
      tags: always
    - name: Set Config data
      ansible.builtin.set_fact:
        config: "{{ config }}"
      tags: always

  tasks:
    - name: Get info for servers by name
      cisco.intersight.intersight_info:
        <<: *api_info
        server_names: []
      register: server_names

    - name: Build Server Output
      ansible.builtin.set_fact:
        server_output: "{{ server_output | default([]) + [{'Name': item.Name, 'Data': {'Moid': item.Moid, 'Memory': item.AvailableMemory, 'CPUCores': item.NumCpuCores, 'CPUCoresEnabled': item.NumCpuCoresEnabled, 'CPUCount': item.NumCpus, 'Dn': item.Dn, 'Firmware': item.Firmware, 'IP': item.Ipv4Address, 'MemorySpeed': item.MemorySpeed, 'Model': item.Model, 'EthInterfaceCount': item.NumEthHostInterfaces, 'FCInterfaceCount': item.NumFcHostInterfaces, 'PowerState': item.OperPowerState, 'Serial': item.Serial}}] }}"
      loop: "{{ server_names.intersight_servers }}"
      loop_control:
        label: All data gathered from Intersight for server {{ item.Name }}

    - name: Update intersight_review server details
      ansible.builtin.set_fact:
        intersight_review: "{{ intersight_review | combine({'intersight': {'server': {'servers': server_output}}}) }}"

    - name:  Get HCL status
      vars:
        task_api_info: "{{ api_info }}"
      ansible.builtin.include_tasks: tasks/hcl.yml
      loop: "{{ (intersight_review | get_value('intersight.server.servers[*]'))[:1] }}"
      # loop: "{{ intersight_review | get_value('intersight.server.servers[*]') }}"
      when: intersight_review is defined




    # - name: Process data for summary infomation
    #   ansible.builtin.import_tasks: tasks/summary.yml
    #   when: intersight_review is defined

    # - name: Debug full report
    #   ansible.builtin.import_tasks: tasks/debug.yml
    #   when: intersight_review is defined

    # - name: Save processed data to XLSX file
    #   ansible.builtin.import_tasks: tasks/save.yml
    #   when: intersight_review is defined
